### ISSUE TITLE
gettext fails to compile with phoenix 1.1

### ISSUE THREAD

**Issue by sokoow** [elixir-lang/gettext#93]
This is similar to, but slightly different than:

https://github.com/elixir-lang/gettext/issues/67
https://github.com/phoenixframework/phoenix/issues/1411

```
mix phoenix.server

== Compilation error on file lib/gettext/backend.ex ==
** (CompileError) lib/gettext/backend.ex:16: undefined function ::/2
    (elixir) expanding macro: Kernel.@/1
    lib/gettext/backend.ex:16: Gettext.Backend (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

==> gettext
could not compile dependency gettext, mix compile failed. You can recompile this dependency with `mix deps.compile gettext` or update it with `mix deps.update gettext`

```

I got erlang-parsetools and erlang-dev installed, and the error is same on ubuntu 15.10 and 16.04. Help please?

**Comment by sokoow** [comment]
it just required newer version of elixir.. all good now
