### ISSUE TITLE
Starting phoenix server crashes over gettext

### ISSUE THREAD

**Issue by buelsenfrucht** [elixir-lang/gettext#163]
OS: MacOS Hight Sierra
Erlang: I tried 20.1, 20.0
Elixir: I tried 1.5.1 and 1.5.2

After updating to macOS High Sierra and installing Erlang 20.1 with asdf, I tried to recompile and start my application with `mix phx.server`, but it crashes with message:

```
== Compilation error on file lib/srce_frontend/web/gettext.ex ==
** (CompileError) Elixir.SRCE.Frontend.Web.Gettext: function lgettext/4+1635:
  Internal consistency check failed - please report this bug.
  Instruction: {test,bs_match_string,{f,423},[{x,7},48,{string,"untry]"}]}
  Error:       {no_bsm_context,{x,7}}:

    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

I tried different combination of Erlang and Elixir, but result was always the same.

Not sure if this is a gettext, Elixir or Erlang issue though...

**Comment by josevalim** [comment]
It should work on Erlang 20.0, this is a bug on Erlang 20.1 which has already been reported upstream.

**Comment by buelsenfrucht** [comment]
You are right, thanks for your help! 
Unfortunately 20.0 isn't working on our project on High Sierra because of the BoringSSL-Bug that is fixed by updating erlang to 20.1...
